/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Car;
import model.CarHistory;



/**
 *
 * @author jharnadoda
 */
public class AddJPanel extends javax.swing.JPanel {

    CarHistory history;
    public AddJPanel(CarHistory history) {
        initComponents();
        this.history=history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_add = new javax.swing.JLabel();
        label_company = new javax.swing.JLabel();
        label_manufacturing_year = new javax.swing.JLabel();
        label_min_seats = new javax.swing.JLabel();
        label_max_seats = new javax.swing.JLabel();
        label_serial_no = new javax.swing.JLabel();
        label_model_no = new javax.swing.JLabel();
        label_city = new javax.swing.JLabel();
        label_maintenence_certi = new javax.swing.JLabel();
        label_availability = new javax.swing.JLabel();
        txt_company = new javax.swing.JTextField();
        txt_manufacturing_year = new javax.swing.JTextField();
        txt_min_seats = new javax.swing.JTextField();
        txt_max_seats = new javax.swing.JTextField();
        txt_serial_no = new javax.swing.JTextField();
        txt_model_no = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        combobox_maintenance_certi = new javax.swing.JComboBox<>();
        combobox_availability = new javax.swing.JComboBox<>();
        button_add = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        label_add.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        label_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_add.setText("Add");

        label_company.setText("Company");

        label_manufacturing_year.setText("Manufacturing Year");

        label_min_seats.setText("Min. Seats");

        label_max_seats.setText("Max. Seats");

        label_serial_no.setText("Serial No");

        label_model_no.setText("Model No");

        label_city.setText("City");

        label_maintenence_certi.setText("Maintenance Certificate");

        label_availability.setText("Availability");

        txt_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_companyActionPerformed(evt);
            }
        });

        txt_manufacturing_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manufacturing_yearActionPerformed(evt);
            }
        });

        txt_min_seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_min_seatsActionPerformed(evt);
            }
        });

        txt_max_seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_max_seatsActionPerformed(evt);
            }
        });

        txt_serial_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serial_noActionPerformed(evt);
            }
        });

        txt_model_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_model_noActionPerformed(evt);
            }
        });

        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        combobox_maintenance_certi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expired", "Not Expired" }));
        combobox_maintenance_certi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_maintenance_certiActionPerformed(evt);
            }
        });

        combobox_availability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));
        combobox_availability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_availabilityActionPerformed(evt);
            }
        });

        button_add.setText("Add");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_company, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_manufacturing_year, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_min_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_max_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_serial_no, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_model_no, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_city, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label_availability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label_maintenence_certi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_manufacturing_year, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txt_min_seats, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txt_max_seats, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txt_serial_no, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txt_model_no, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txt_city, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(combobox_maintenance_certi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combobox_availability, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(button_add)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_company, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_manufacturing_year, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_manufacturing_year, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_min_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_min_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_max_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_max_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_serial_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_serial_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_model_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_model_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_city, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_maintenence_certi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_maintenance_certi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_availability, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_availability, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(button_add)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_companyActionPerformed
        // TODO add your handling code here:
        String c=txt_company.getText();
        if(c=="")
        {
            
        }
    }//GEN-LAST:event_txt_companyActionPerformed

    private void txt_manufacturing_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manufacturing_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manufacturing_yearActionPerformed

    private void txt_min_seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_min_seatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_min_seatsActionPerformed

    private void txt_max_seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_max_seatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_max_seatsActionPerformed

    private void txt_serial_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serial_noActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txt_serial_noActionPerformed

    private void txt_model_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_model_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_model_noActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void combobox_maintenance_certiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_maintenance_certiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_combobox_maintenance_certiActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        // TODO add your handling code here:
        if(txt_manufacturing_year.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(this, "Please add Manufacturing year");
            return;
        }
        
        for(Car c: history.getHistory())
        {
            if(txt_serial_no.getText().equalsIgnoreCase(String.valueOf(c.getSerial_no())))
            { //validation
                JOptionPane.showMessageDialog(this,"Serial no already exists");
                return;
            }
        }
        
        
        String company=txt_company.getText();
        int manufacturing_year=Integer.parseInt(txt_manufacturing_year.getText());
        int min_seats=Integer.parseInt(txt_min_seats.getText());
        int max_seats=Integer.parseInt(txt_max_seats.getText());
        int serial_no=Integer.parseInt(txt_serial_no.getText());
        String model_no=txt_model_no.getText();
        String city=txt_city.getText();
        String maintenance_certificate = (String)combobox_maintenance_certi.getSelectedItem();
        String availability = (String)combobox_availability.getSelectedItem();
        
        Car add=history.addCar();
        
        add.setCompany(company);
        add.setManufacturing_year(manufacturing_year);
        add.setMin_seats(min_seats);
        add.setMax_seats(max_seats);
        add.setSerial_no(serial_no);
        add.setModel_no(model_no);
        add.setCity(city);
        add.setMaintenance_certi(maintenance_certificate);
        add.setAvailability(availability);
        
        JOptionPane.showMessageDialog(null,"New Entry Added");
        txt_company.setText("");
        txt_manufacturing_year.setText("");
        txt_min_seats.setText("");
        txt_max_seats.setText("");
        txt_serial_no.setText("");
        txt_model_no.setText("");
        txt_city.setText("");
        
        
        
       
        
        
    }//GEN-LAST:event_button_addActionPerformed

    private void combobox_availabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_availabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_availabilityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JComboBox<String> combobox_availability;
    private javax.swing.JComboBox<String> combobox_maintenance_certi;
    private javax.swing.JLabel label_add;
    private javax.swing.JLabel label_availability;
    private javax.swing.JLabel label_city;
    private javax.swing.JLabel label_company;
    private javax.swing.JLabel label_maintenence_certi;
    private javax.swing.JLabel label_manufacturing_year;
    private javax.swing.JLabel label_max_seats;
    private javax.swing.JLabel label_min_seats;
    private javax.swing.JLabel label_model_no;
    private javax.swing.JLabel label_serial_no;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_company;
    private javax.swing.JTextField txt_manufacturing_year;
    private javax.swing.JTextField txt_max_seats;
    private javax.swing.JTextField txt_min_seats;
    private javax.swing.JTextField txt_model_no;
    private javax.swing.JTextField txt_serial_no;
    // End of variables declaration//GEN-END:variables
}
