/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.CarHistory;

/**
 *
 * @author jharnadoda
 */
public class MainJFrame extends javax.swing.JFrame {

    CarHistory history;
    
    public MainJFrame() {
        initComponents();
        history= new CarHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        button_view = new javax.swing.JButton();
        button_add = new javax.swing.JButton();
        search_by_availability = new javax.swing.JButton();
        search_by_year = new javax.swing.JButton();
        search_by_company = new javax.swing.JButton();
        search_by_seats = new javax.swing.JButton();
        search_by_model = new javax.swing.JButton();
        search_by_serial = new javax.swing.JButton();
        search_by_city = new javax.swing.JButton();
        search_by_city1 = new javax.swing.JButton();
        list_manu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.black, null, null));

        button_view.setText("View");
        button_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_viewActionPerformed(evt);
            }
        });

        button_add.setText("Add");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        search_by_availability.setText("Search by Availability");
        search_by_availability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_availabilityActionPerformed(evt);
            }
        });

        search_by_year.setText("Search by Year");
        search_by_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_yearActionPerformed(evt);
            }
        });

        search_by_company.setText("Search by Company");
        search_by_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_companyActionPerformed(evt);
            }
        });

        search_by_seats.setText("Search by Number of Seats");
        search_by_seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_seatsActionPerformed(evt);
            }
        });

        search_by_model.setText("Search by Model No");
        search_by_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_modelActionPerformed(evt);
            }
        });

        search_by_serial.setText("Search by Serial No");
        search_by_serial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_serialActionPerformed(evt);
            }
        });

        search_by_city.setText("Search by City");
        search_by_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_cityActionPerformed(evt);
            }
        });

        search_by_city1.setText("Search by Maintenance Certificate");
        search_by_city1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_city1ActionPerformed(evt);
            }
        });

        list_manu.setText("List All Manufacturers");
        list_manu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_manuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list_manu, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(search_by_city1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                        .addComponent(search_by_city, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(search_by_model, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(search_by_seats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(search_by_year, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_by_company, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_by_availability, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(search_by_serial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_view, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(search_by_availability, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_by_company, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_by_year)
                .addGap(4, 4, 4)
                .addComponent(search_by_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_by_model, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_by_serial)
                .addGap(4, 4, 4)
                .addComponent(search_by_city)
                .addGap(4, 4, 4)
                .addComponent(search_by_city1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_manu)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.blue, null, null));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("UBER Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_viewActionPerformed
       ViewJPanel viewPanel=new ViewJPanel(history);
       splitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_button_viewActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        AddJPanel addPanel=new AddJPanel(history);
        splitPane.setRightComponent(addPanel);
    }//GEN-LAST:event_button_addActionPerformed

    private void search_by_availabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_availabilityActionPerformed
        // TODO add your handling code here:
        availabilityJPanel availabilityPanel=new availabilityJPanel(history);
        splitPane.setRightComponent(availabilityPanel);
        
    }//GEN-LAST:event_search_by_availabilityActionPerformed

    private void search_by_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_yearActionPerformed
        // TODO add your handling code here:
        YearJPanel yearPanel=new YearJPanel(history);
        splitPane.setRightComponent(yearPanel);
    }//GEN-LAST:event_search_by_yearActionPerformed

    private void search_by_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_companyActionPerformed
        // TODO add your handling code here:
       CompanyJPanel companyPanel=new CompanyJPanel(history);
        splitPane.setRightComponent(companyPanel);
    }//GEN-LAST:event_search_by_companyActionPerformed

    private void search_by_seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_seatsActionPerformed
        // TODO add your handling code here:
        
        SeatsJPanel seatsPanel=new SeatsJPanel(history);
        splitPane.setRightComponent(seatsPanel);

    }//GEN-LAST:event_search_by_seatsActionPerformed

    private void search_by_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_modelActionPerformed
        // TODO add your handling code here:
        ModelJPanel modelPanel=new ModelJPanel(history);
        splitPane.setRightComponent(modelPanel);
    }//GEN-LAST:event_search_by_modelActionPerformed

    private void search_by_serialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_serialActionPerformed
        // TODO add your handling code here:
        SerialJPanel serialPanel=new SerialJPanel(history);
        splitPane.setRightComponent(serialPanel);
    }//GEN-LAST:event_search_by_serialActionPerformed

    private void search_by_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_cityActionPerformed
        // TODO add your handling code here:
        CityJPanel cityPanel=new CityJPanel(history);
        splitPane.setRightComponent(cityPanel);
    }//GEN-LAST:event_search_by_cityActionPerformed

    private void search_by_city1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_city1ActionPerformed
        // TODO add your handling code here:
        ExpiredJPanel expiredPanel=new ExpiredJPanel(history);
        splitPane.setRightComponent(expiredPanel);
    }//GEN-LAST:event_search_by_city1ActionPerformed

    private void list_manuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_manuActionPerformed
        // TODO add your handling code here:
        AllManufacturersJPanel AllManufacturersPanel=new AllManufacturersJPanel(history);
        splitPane.setRightComponent(AllManufacturersPanel);
    }//GEN-LAST:event_list_manuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton list_manu;
    private javax.swing.JButton search_by_availability;
    private javax.swing.JButton search_by_city;
    private javax.swing.JButton search_by_city1;
    private javax.swing.JButton search_by_company;
    private javax.swing.JButton search_by_model;
    private javax.swing.JButton search_by_seats;
    private javax.swing.JButton search_by_serial;
    private javax.swing.JButton search_by_year;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
